name: lockin
description: "A new Flutter project."

publish_to: 'none'

version: 1.1.5+38

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  simple_gesture_detector: ^0.2.1
  uuid: ^4.4.2
  google_mobile_ads: ^6.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  permission_handler: ^12.0.1
  share_plus: ^8.0.3
  file_picker: ^8.0.3
  path_provider: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_rendered.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon_rendered.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/splash_rendered_notext.png"
  android: true
  ios: true

  android_12:
    color: "#000000"
    image: "assets/splash_rendered_notext.png"
    icon_background_color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/